// samples/nuxt-sample/pages/profile.vue
<script setup lang="ts">
import { CreateLightAuthClient } from "@light-auth/nuxt/client";
const { getSession } = CreateLightAuthClient();
const session = await getSession();
</script>

<template>
  <div>
    <div class="max-w-md mx-auto bg-white rounded-lg shadow-md p-8">
      <div class="text-center" v-if="session != null">
        <h1 class="text-2xl font-bold mb-4">You are logged in!</h1>
        <p class="text-gray-600 mb-6 text-center" v-if="session != null">{{ session.email }}</p>
      </div>
      <div class="text-center" v-if="session == null">
        <h1 class="text-2xl font-bold mb-4">You are not logged in!</h1>
        <a
          href="/login"
          class="w-full flex items-center justify-center gap-3 px-4 py-3 bg-white border border-gray-300 rounded-md hover:bg-gray-50 transition-colors"
        >
          Login
        </a>
      </div>
    </div>
  </div>
</template>

// samples/nextjs-sample/app/profile/page.tsx
import Link from "next/link";
import { getSession, getUser } from "@/lib/auth";

export default async function Home() {
  const session = await getSession();
  const user = await getUser();

  // Check if user is logged in from cookies

  return (
    <div className="min-h-screen flex flex-col container mx-auto p-8 max-w-4xl">
      <h1 className="text-3xl font-bold mb-6">Profile Page</h1>

      <div className="bg-white shadow-md rounded-lg p-6 border border-gray-200">
        <h2 className="text-xl font-semibold mb-4">Login Status</h2>

        {session != null ? (
          <div className="space-y-4">
            <div className="p-4 bg-green-50 text-green-700 rounded-md">
              <p className="font-medium">✅ You are logged in!</p>
            </div>

            <div className="space-y-2">
              <h3 className="font-medium">Session:</h3>
              <div className="bg-gray-50 p-4 rounded-md">
                <pre className="whitespace-pre-wrap text-sm break-all ">
                  {JSON.stringify(session, null, 2)}
                </pre>
              </div>
            </div>
            <div className="space-y-2">
              <h3 className="font-medium">User:</h3>
              <div className="bg-gray-50 p-4 rounded-md">
                <pre className="whitespace-pre-wrap text-sm break-all ">
                  {JSON.stringify(user, null, 2)}
                </pre>
              </div>
            </div>
          </div>
        ) : (
          <div className="space-y-4">
            <div className="p-4 bg-yellow-50 text-yellow-700 rounded-md">
              <p className="font-medium">⚠️ You are not logged in</p>
            </div>

            <div className="mt-4">
              <Link
                href="/login"
                className="inline-flex items-center px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
              >
                Go to Login Page
              </Link>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
